export { AimIcon } from './Aim'
export { CaseIcon } from './Case'
export { FaceIcon } from './Face'
export { GamesIcon } from './Games'
export { RatingIcon } from './Rating'
export { ServicesIcon } from './Services'
export { SpinIcon } from './Spin'
export { StormIcon } from './Storm'
export { SwitchIcon } from './Switch'
export { TasksIcon } from './Tasks'
export { TournamentsIcon } from './Tournaments'
export { WorkShopIcon } from './WorkShop'
export type { IconProps } from './types'
